"""empty message

Revision ID: 2efac883206f
Revises: 13289316db40
Create Date: 2021-03-22 12:45:24.130143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2efac883206f'
down_revision = '13289316db40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoples_in_trees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peoples_in_trees_user_id'), 'peoples_in_trees', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peoples_in_trees_user_id'), table_name='peoples_in_trees')
    op.drop_table('peoples_in_trees')
    # ### end Alembic commands ###
