"""empty message

Revision ID: 50cdb60802f7
Revises: f7d835941827
Create Date: 2021-04-08 21:50:15.641044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cdb60802f7'
down_revision = 'f7d835941827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peoples_in_trees', sa.Column('description', sa.String(length=256), nullable=True))
    op.add_column('peoples_in_trees', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.drop_column('peoples_in_trees', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peoples_in_trees', sa.Column('photo', sa.BLOB(), nullable=True))
    op.drop_column('peoples_in_trees', 'image')
    op.drop_column('peoples_in_trees', 'description')
    # ### end Alembic commands ###
