"""empty message

Revision ID: 7232cdea47cc
Revises: 50cdb60802f7
Create Date: 2021-04-08 22:00:04.423072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7232cdea47cc'
down_revision = '50cdb60802f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_user_id'), 'human', ['user_id'], unique=False)
    op.drop_index('ix_peoples_in_trees_user_id', table_name='peoples_in_trees')
    op.drop_table('peoples_in_trees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peoples_in_trees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('photo', sa.BLOB(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('image', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_peoples_in_trees_user_id', 'peoples_in_trees', ['user_id'], unique=False)
    op.drop_index(op.f('ix_human_user_id'), table_name='human')
    op.drop_table('human')
    # ### end Alembic commands ###
