"""empty message

Revision ID: af9650e0663d
Revises: e84adc98c29b
Create Date: 2021-05-03 21:35:10.183899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9650e0663d'
down_revision = 'e84adc98c29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('date_of_bithday', sa.Date(), nullable=True))
    op.add_column('human', sa.Column('date_of_death', sa.Date(), nullable=True))
    op.add_column('human', sa.Column('is_alive', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human', 'is_alive')
    op.drop_column('human', 'date_of_death')
    op.drop_column('human', 'date_of_bithday')
    # ### end Alembic commands ###
