"""empty message

Revision ID: e84adc98c29b
Revises: 7232cdea47cc
Create Date: 2021-04-08 22:21:26.236612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84adc98c29b'
down_revision = '7232cdea47cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('parent_id_1', sa.Integer(), nullable=True))
    op.add_column('human', sa.Column('parent_id_2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human', 'parent_id_2')
    op.drop_column('human', 'parent_id_1')
    # ### end Alembic commands ###
