"""empty message

Revision ID: f7d835941827
Revises: 2efac883206f
Create Date: 2021-04-07 16:17:41.256995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d835941827'
down_revision = '2efac883206f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peoples_in_trees', sa.Column('photo', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peoples_in_trees', 'photo')
    # ### end Alembic commands ###
